"""Module, containing game configurations."""
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

SKY_COLOR = (0, 0, 255)

BRICK_SIZE = 40
GROUND_Y_POSITION = SCREEN_HEIGHT - BRICK_SIZE * 3 // 2

CAT_MAX_X_SPEED = 360
CAT_MAX_Y_SPEED = 360
CAT_WALK_ACCELERATION = 300
CAT_CHANGE_DIRECTION_ACCELERATION = 600
CAT_JUMP_SPEED = -300
CAT_ENEMY_KILLING_JUMP_SPEED = -600
GRAVITY = 700
JUMP_GRAVITY = 300
